name: Deploy Infrastructure

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  terraform:
    name: Deploy Site
    runs-on: ubuntu-latest
    env:
      working-directory: terraform-management
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: ${{ env.working-directory }}

    - name: Terraform Validate
      id: validate
      run: terraform validate

    - name: Terraform plan
      id: plan
      run: terraform plan -no-color
      working-directory: ${{ env.working-directory }}
